meesho:
  pdf:
    x: 0
    y: 550
    height: 1000
    width: 1000
flipkart:
  pdf:
    x: 150
    y: -1
    height: 360
    width: 300
    offset: 0
springdoc:
  swagger-ui:
    path: /api

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus